# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logging.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlogging.proto\"\x84\x01\n\nLogRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\r\n\x05juego\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x11\n\tteam_name\x18\x05 \x01(\t\x12\x13\n\x0bplayer_name\x18\x06 \x01(\t\x12\x0c\n\x04roll\x18\x07 \x01(\t\"\x1d\n\x0bLogResponse\x12\x0e\n\x06status\x18\x01 \x01(\t21\n\rLoggerService\x12 \n\x03Log\x12\x0b.LogRequest\x1a\x0c.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGREQUEST']._serialized_start=18
  _globals['_LOGREQUEST']._serialized_end=150
  _globals['_LOGRESPONSE']._serialized_start=152
  _globals['_LOGRESPONSE']._serialized_end=181
  _globals['_LOGGERSERVICE']._serialized_start=183
  _globals['_LOGGERSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
